### PR TITLE
Simpel pdf extractor

### PR DESCRIPTION
**Pull request by auchri**
Implement pdf extractor for sell/buy transactions of [Simpel S.A.](https://www.simpel.lu) ([Own360](https://www.own360.app/)).

### CODE REVIEW

**Comment by buchen** [comment]
Nice. I see the pull request is marked as "draft". Do you have particular questions?

The build fails because of code formatting. That is typically easy to fix within Eclipse because Eclipse should pick up the PP code style of the project automatically. If you reformat the file, it should be fixed.

And I propose to delete the commented out section of code.

@Nirus2000 can you also have a look at it?

**Comment by auchri** [comment]
Hi @buchen ,

I also want to add the implementations for sell and dividend transactions, that's why I marked the PR as draft.

**Comment by auchri** [comment]
Buy and sell transactions are implemented now, PR is ready for review @buchen :)

**Comment by auchri** [comment]
I'm not sure if the buy transaction is correct.
In the pdf it is stated that 0,071 shares are buyed at a fund price of 140,59€ (which would be 9,982€ but it's a savings plan with 10€ and also 10€ are debited from the bank account).

So is it more correct to import the transaction with the amount of 9,98€ (like it is at the moment) or with the amount of 10€ and a different fund price?

**Comment by auchri** [comment]
Hi @buchen, I removed the "Steuerlicher Anschaffungswert", the previous example is imported with 10€ now. I think that's correct.

**Comment by buchen** [comment]
Thanks @auchri for the new PDF importer.
I have merged the changes :-)

**Pull request closed without merging**
