### PR TITLE
Fix SelfWeath PDF-Importer to support hidden blank characters

### PR DESCRIPTION
**Pull request by Nirus2000**
Fix SelfWeath PDF-Importer to support hidden blank characters
https://forum.portfolio-performance.info/t/pdf-import-from-selfwealth/17399/9

### CODE REVIEW

**Comment by flywire** [comment]
**Seems not the preferred solution.** Preferred solution previously discussed would strip the nbsp characters from PDFBox output before applying regex.

---

No reply to my previous unanswered [query asking if I can test code without compiling](https://github.com/buchen/portfolio/pull/2386#issuecomment-896356395) so I assume this is just a regex change. It will retain [invisible] NBSP characters in the file and only cause ongoing issues for users.

Findings of investigation in https://github.com/buchen/portfolio/pull/2340#issuecomment-888269417 with PDFBox developer recommendation:
> if you don't like it, do your own postprocessing. It's unusual but valid.

https://github.com/buchen/portfolio/pull/2340#issuecomment-892377110
@buchen
> From my point of view, there are two options:

https://github.com/buchen/portfolio/pull/2340#issuecomment-892384513
> My preference is do a post-processing and replace the non-breaking spaces with regular spaces and given they are not normally visible (unless in hex) I suggest do it on all files. Would also give same result as select/copy/paste from pdf file.

**Comment by Nirus2000** [comment]
I think this will be the last pull request for me for the SelfWeath importer. That is the end of the subject for me. You have now replied to the same commit multiple times, each time making the same links to the same comments, and so on. We have read this several times. If the PDF is read out correctly using the PDF debug, then we see the problems.
It is strange that the "hide" spaces do not exist and that with this pull request, the test files that "hide" spaces are present.
You could have solved the problem yourself in pull request # 2340, but you didn't. Instead, I am trying to work out a solution and so far all of the PDF debug you have created have gone through correctly.
What are correct and what are wrong PDF debugs ?!
We can only work with correct PDF debugs, but according to you, you only provide incorrect PDF debugs? So...?!

Kind regards
Alex

**Comment by flywire** [comment]
@Nirus2000 I realise you have gone to a lot of effort to fix and I thank you for that. You have delivered a solid workaround for csv's. Unfortunately, the two-way communication has been ineffective and the technical issues I raised regarding &NBSP characters haven't been given enough consideration.

> You could have solved the problem yourself in pull request #2340

How? @buchen identified &NBSPs, made a quick fix which unfortunately turned out wrong and closed the commit. Surely my communication has been clear to strip the &NBSP characters and leave the regex.

**Comment by buchen** [comment]
I have slightly adopted the change and implemented the generic removal of horizontal spaces from all files.

**Pull request closed without merging**
