### PR TITLE
Stake pdf loader

### PR DESCRIPTION
**Pull request by flywire**
https://hellostake.com/au

Note:
1. Security uses ticker code with `.ASX` extension
2. No security name
3. `A$` is `AUD` currency
4. Summary at top of file can be ignored

### CODE REVIEW

**Comment by buchen** [comment]
@flywire  I think the commit is missing the actual PDF Importer (StakePDFExtractor)

**Comment by Nirus2000** [comment]
@flywire 
please take a look at this [post](https://github.com/buchen/portfolio/pull/3354#issuecomment-1547193772) before you go any further. So change the test cases to the newer version and apply the Contributing standards.

**Comment by flywire** [comment]
@Nirus2000 How can I get a 3 character currency from a single character as shown above?

> apply the Contributing standards

Already using them. They need a mention of `//` <-> `/` conversion in https://regex101.com/
> change the test cases to the newer version

I'm not clear on that currently, I'll have to come back to it.

**Comment by buchen** [comment]
> How can I get a 3 character currency from a single character as shown above?

@flywire 

Although PP is not really using this at the moment, the ```CurrencyUnit``` class knows about the currency symbols - including A$.

https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/money/currencies.properties#L44

Feel free to add an appropriate static lookup method to CurrencyUnit (or check in the importer-specific code)

**Comment by buchen** [comment]
> change the test cases to the newer version

We added a couple of custom Hamcrest matchers to make the tests more concise.

See here for example:
https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/dekabank/DekaBankPDFExtractorTest.java#L21652-L21655

**Comment by flywire** [comment]
> add an appropriate static lookup method to CurrencyUnit (or check in the importer-specific code

I think you misunderstand my contribution, I'm not writing java code, just pattern patching with the docs and existing code to adapt it to a new broker. I know what a static method is but I don't write them. If you could point me to a good code example I could likely work it in.

If I can get this broker done I'll add another one.

**Comment by buchen** [comment]
> I'm not writing java code, just pattern patching with the docs and existing code to adapt it to a new broker.

As you are not writing code, the code looks good ;-) Let me have a look at it the next days

**Comment by buchen** [comment]
@flywire 

I adopted the code to make it work with your examples.

However, I have couple of questions we can discuss here in this pull request:

First about the currency of the investment vehicle.
```
QUANTITY 512
EFFECTIVE PRICE $20.43 TICKER FLT.ASX
VALUE A$10,455.04 EXECUTION DATE 27-05-2022
ORDER TYPE LIMIT HIN 12345678
```
Interestingly it says "$" as effective price and "A$". Is the vehicle traded in USD? I do not think because the exchange rate would make this sum up. So I assume that it is just missing the "A". For now, I pick up the currency of the investment vehicle also from the "VALUE" line. Do you think that is okay?

Interestingly the numbers also do not add up. If it is 512 pieces at 20.43, I'd expect a different value:
512 * 20.43 = 10,460.16  != 10,455.04
For now I ignore the share price (PP will calculate it by dividing the given total of  10,455.04)
Do you have an idea where the difference could come from?

```
"^EFFECTIVE PRICE \\p{Sc}[\\.,\\d]+ TICKER (?<tickerSymbol>[\\w]{3,4})\\.ASX$"
```
Here you are only matching the ticker, but not the exchange suffix (here: ASX). This value is used to find the existing investment vehicle in the existing PP file. Because the ticker is also used to retrieve historical prices, I would assume the configured ticker actually includes the exchange suffix. Therefore my gut feeling is: should the ticker be matched so that it incudes the exchange?

**Comment by flywire** [comment]
> As you are not writing code, the code looks good ;-)

Credit to @Nirus2000 and @buchen for ongoing improvements to the PDF importer documentation and code comments to support hacking by non-java programmers

---

> First about the currency of the investment vehicle.

Effective price does not display currency, just currency sign. The currency is `AUD` in this example.

>  the numbers also do not add up. If it is 512 pieces at 20.43

Hmm, misplaced keystroke changed one and I made the other wrong when I went to fix it, original is `$20.42`. btw, I notice another contract note effective price has `$9.9999` format, dollar to 4 decimal places.

> Here you are only matching the ticker, but not the exchange suffix (here: ASX).

This is something I don't understand. I use Yahoo as the quote provider and it uses `.AX` for the `.ASX` exchange. Initially, I enter a security without the exchange suffix, and then when the Quote Feed Exchange is selected as say `FLT.AX (Australian Stock Exchange (ASX))` the `.AX` is appended to the `symbol`.

This becomes a problem entering dividends. `Date,Ticker Symbol,Value,Cash Account` does not recognise the security based on `Ticker Symbol` (with or without the exchange extension), it must be imported with the `Security Name` field. This is difficult to match character perfectly, especially when the dividend payment lists the ticker symbol (without the extension) and not the security name. Essentially, I need to export PP securities, lookup the security name from ticker symbol given in dividend payment then add it to the csv import file. Crazy stuff!

**Comment by buchen** [comment]
> This is something I don't understand. I use Yahoo as the quote provider and it uses ```.AX``` for the ```.ASX``` exchange.

Yeah, I guess this is called "technical debt". Years back I did not realize it needs multiple fields.

But what we can do is this: when looking for a security, we first try to match it by the full entry of the "tickerSymbol". If that does not work, we try to match it by the prefix (strip away the exchange label).

In your case that would mean:
* the security is configured as XYZ.AX (to get prices from Yahoo)
* the PDF document contains XYZ.ASX, we look for the XZY and find the security above

> This becomes a problem entering dividends

How do you enter dividends? Also via PDF import? Or via CSV?

**Comment by buchen** [comment]
> But what we can do is this: when looking for a security, we first try to match it by the full entry of the "tickerSymbol". If that does not work, we try to match it by the prefix (strip away the exchange label).

I realize that @Nirus2000 has already implemented this feature.
[I have added a test that shows that the importer matches an existing security with the ticker FLT.AX to the Buy01.txt import](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/stake/StakePDFExtractorTest.java#L67-L71).

@flywire Which leaves the question why this matching logic does not work for your dividend import workflow. Via PDF? Via CSV?

**Comment by flywire** [comment]
My comments above were not accurate and have been edited. Moved the discussion about Loading Payments by CSV to #3380.

What is required to close this issue?

**Comment by buchen** [comment]
> My comments above were not accurate and have been edited. Moved the discussion about Loading Payments by CSV to https://github.com/buchen/portfolio/issues/3380.

Great. Let me have a look at the other issue then.


> What is required to close this issue?

Nothing. The code is merged already. I just kept it open to not loose the conversation if it is moved to the "closed" section.

**Pull request closed without merging**
