### PR TITLE
Added transaction matcher for Hamcrest assertThat statements

### PR DESCRIPTION
**Pull request by buchen**
Hi @Nirus2000,

I was thinking about how to reduce the boilerplate code needed for the PDF test cases.

With this change, I have tested a couple of custom matchers which can be used with the JUnit ```assertThat```.
It works either for the whole list of result items:

```java
// check dividends transaction
assertThat(results, hasItem(dividend( //
                withDate("2014-12-15"), //
                withShares(380), //
                withSource("Dividende01.txt"), //
                withNote(null), //
                withAmount("EUR", 64.88), //
                withGrossValue("EUR", 87.13), //
                withForexGrossValue("USD", 98.80), //
                withTaxes("EUR", 8.71 + 0.47 + 13.07), //
                withFees("EUR", 0))));
```

or with individual attributes
```java
assertThat(transaction, withAmount("EUR", 16.17));
```

I also tried to make the error messages as readable as possible. This is how the look like. Unfortunately, Infinitest removes the line breaks, but I guess that is okay.

Bildschirmfoto 2023-04-30 um 12 38 04

Bildschirmfoto 2023-04-30 um 12 39 00

Bildschirmfoto 2023-04-30 um 12 39 20

What do you think?

(I think we should **not** change all tests at once, but when writing new tests, we could test this approach and then apply it to more tests over time)

Additionally, in the tests we should just use "EUR" or "USD" as string constants. That is much more readable than CurrencyUnit.EUR. The values should never change anyway. And this way the tests are much more readable

### CODE REVIEW

**Comment by buchen** [comment]
You can add the class to the favorites for static imports so that Eclipse is suggesting the matchers:

Bildschirmfoto 2023-04-30 um 13 14 41

**Comment by buchen** [comment]
And one more thing: the default ```hasItems``` check returns okay for the first match. If one ones to check that exactly 2 transactions with identical properties exist, then one would have to create two sublists of the result items and check them separately.

**Comment by Nirus2000** [comment]
This looks fantastic and would save me an incredible amount of work. :yellow_heart::yellow_heart::yellow_heart:

THAT'S WHAT I WANT... :rofl::rofl::rofl:

I would be happy about a simplification of this part....
```
 results.stream().filter(i -> !(i instanceof SecurityItem))
                        .forEach(i -> assertThat(i.getAmount(), notNullValue()));

        List<Item> securityItems = results.stream().filter(SecurityItem.class::isInstance) //
                        .collect(Collectors.toList());
        List<Item> buySellTransactions = results.stream().filter(BuySellEntryItem.class::isInstance) //
                        .collect(Collectors.toList());
        List<Item> accountTransactions = results.stream().filter(TransactionItem.class::isInstance) //
                        .collect(Collectors.toList());

        assertThat(errors, empty());
        assertThat(securityItems.size(), is(2));
        assertThat(buySellTransactions.size(), is(2));
        assertThat(accountTransactions.size(), is(0));
        assertThat(results.size(), is(4));
        new AssertImportActions().check(results, CurrencyUnit.EUR);
```
to
```
 assertThat(results, hasItem(result(
                                         withSecurity(1), // Count of Securities
                                         withBuySell(1), // Count of buySellTransactions 
                                         withAccount(1), // Count of accountTransactions 
                                         withCancellation(1), // Count of cancellations
                                         withAssertImportActions("EUR") // CheckIT
);
```

Is it possible to reduce this even further in:
from:
```
        // check dividends transaction
        assertThat(results, hasItem(dividend( //
                        withDate("2014-12-15"), //
                        withShares(380), //
                        withSource("Dividende01.txt"), //
                        withNote(null), //
                        withAmount("EUR", 64.88), //
                        withGrossValue("EUR", 87.13), //
                        withTaxes("EUR", 8.71 + 0.47 + 13.07), //
                        withFees("EUR", 0), //
                        check(tx -> {
                            CheckCurrenciesAction c = new CheckCurrenciesAction();
                            Account account = new Account();
                            account.setCurrencyCode(CurrencyUnit.EUR);
                            Status s = c.process((AccountTransaction) tx, account);
                            assertThat(s, is(Status.OK_STATUS));
                        }))));
```
to this? Das ist kurz... und hat alle Informationen...
```
        // check dividends transaction
        assertThat(results, hasItem(DIV("2014-12-15"), (380), ("EUR", 64.88), ("EUR", 87.13), ("EUR", 8.71 + 0.47), ("EUR", 0), ("EUR")

        and the forex gross... (if Security is in USD)...
```

_I know... reach your little finger and take your whole hand...._

**Comment by buchen** [comment]
```java
 assertThat(results, hasItem(result(
                                         withSecurity(1), // Count of Securities
                                         withBuySell(1), // Count of buySellTransactions 
                                         withAccount(1), // Count of accountTransactions 
                                         withCancellation(1), // Count of cancellations
                                         withAssertImportActions("EUR") // CheckIT
);
```

This syntax is not easy to archive because matchers work on individual items, not the whole list.

What is possible is
```java
        assertThat(countAccountTransactions(results), is(31L));
```

With a simple implementation in a helper
```java
    public static long countAccountTransactions(List<Extractor.Item> items)
    {
        return items.stream().filter(TransactionItem.class::isInstance).count();
    }
```

Although from a cost/benefit point of view, it saving not so much anymore.

**Comment by buchen** [comment]
```
results.stream().filter(i -> !(i instanceof SecurityItem))
                        .forEach(i -> assertThat(i.getAmount(), notNullValue()));
```

I am not sure that this test is needed at all. The import actions check for the currency. I think you do not have to check for this in the pdf tests.

**Comment by buchen** [comment]
```
// check dividends transaction
        assertThat(results, hasItem(DIV("2014-12-15"), (380), ("EUR", 64.88), ("EUR", 87.13), ("EUR", 8.71 + 0.47), ("EUR", 0), ("EUR"), ("Dividende01.txt")

        and the forex gross... (if Security is in USD)...
```

This is not java syntax, but I get your intention. I would be careful about only "positional" knowledge. Here one needs to know that the 5th place is taxes. Already the CSV tests drive me crazy because they are so hard to maintain. Plus, I would not test all properties all the time - only the relevant ones.

We could collapse it into one or two lines... but personally I think it does not increase readability. 

```java
// check dividends transaction
assertThat(results, hasItem(dividend( //
                withDate("2014-12-15"), withShares(380), withSource("Dividende01.txt"), withNote(null), //
                withAmount("EUR", 64.88), withGrossValue("EUR", 87.13), withForexGrossValue("USD", 98.80), //
                withTaxes("EUR", 8.71 + 0.47 + 13.07), withFees("EUR", 0))));
```

**Comment by Nirus2000** [comment]
Okay...I understand your comments.

**How can I skip transactions?**
for example in Bondora Go & Grow
I want to test only transaction 4, 7 and 19.

**Is this possible?**
`withCancellation(1), // Count of cancellations`

---

Can you still implement this type of testing?

(Dividende + Tax Refund + Delivery Inbound)
https://github.com/buchen/portfolio/blob/21334c1e4668b2809170f35c986b3023ae797bb2/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/fintechgroupbank/FinTechGroupBankPDFExtractorTest.java#L3764

(Removal, Interest, Interest cancellation)
https://github.com/buchen/portfolio/blob/21334c1e4668b2809170f35c986b3023ae797bb2/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/fintechgroupbank/FinTechGroupBankPDFExtractorTest.java#L2651

(BuySell cancallation)
https://github.com/buchen/portfolio/blob/21334c1e4668b2809170f35c986b3023ae797bb2/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/fintechgroupbank/FinTechGroupBankPDFExtractorTest.java#L1296

(Dividende cancallation)
https://github.com/buchen/portfolio/blob/21334c1e4668b2809170f35c986b3023ae797bb2/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/baaderbank/BaaderBankPDFExtractorTest.java#L2765

---

I would then just start working with it .
To do this I would just rewrite some tests to the new format and start a PR, if I have problems with it then we will see how we can solve them.

The fact is... that this would help us a lot. 

Regards
Alex

**Comment by buchen** [comment]
> Can you still implement this type of testing?

I have added the matchers (and adopted the linked test cases) with 02f002f5b457cb695d897c0595c38a846818fe7f
I think it should be fairly straightforward to add additional types as necessary


@Nirus2000 However, as part of the tests, I noticed this tests case in FinTech - a buySell with a type TRANSFER_OUT. That is inconsistent. In the model, a transfer must be have a PortfolioTransferEntry (and not BuySellEntry) and it must be a PortfolioTransferEntryItem (and not BuySellEntryItem).

I am not sure what this transactions is supposed to be. With the amount of zero, it sounds more like a "outbound delivery" with zero amount. What do you think?

And then we should check: a) do we need code that fixes existing files for the user and b) to what should we fixe it (to buy sell, because it has the account transaction? Or a delivery outbound? We cannot fix it to a transfer because a transfer requires *two* portfolios which we cannot automatically determine).

```java
        // check 1st transfer_out transaction
        BuySellEntry entry = (BuySellEntry) results.stream().filter(BuySellEntryItem.class::isInstance).findFirst()
                        .orElseThrow(IllegalArgumentException::new).getSubject();

        assertThat(entry.getPortfolioTransaction().getType(), is(PortfolioTransaction.Type.TRANSFER_OUT));
        assertThat(entry.getAccountTransaction().getType(), is(AccountTransaction.Type.TRANSFER_OUT));

        assertThat(entry.getPortfolioTransaction().getDateTime(), is(LocalDateTime.parse("2010-03-16T00:00")));
        assertThat(entry.getPortfolioTransaction().getShares(), is(Values.Share.factorize(2000)));
        assertThat(entry.getSource(), is("FinTechWertpapierAusgang03.txt"));
        assertThat(entry.getNote(), is("Transaktion-Nr.: 223770199"));

        assertThat(entry.getPortfolioTransaction().getMonetaryAmount(),
                        is(Money.of(CurrencyUnit.EUR, Values.Amount.factorize(0.00))));
        assertThat(entry.getPortfolioTransaction().getGrossValue(),
                        is(Money.of(CurrencyUnit.EUR, Values.Amount.factorize(0.00))));
        assertThat(entry.getPortfolioTransaction().getUnitSum(Unit.Type.TAX),
                        is(Money.of(CurrencyUnit.EUR, Values.Amount.factorize(0.00))));
        assertThat(entry.getPortfolioTransaction().getUnitSum(Unit.Type.FEE),
                        is(Money.of(CurrencyUnit.EUR, Values.Amount.factorize(0.00))));
```

**Pull request merged**
