### PR TITLE
Description dashboard widget

### PR DESCRIPTION
**Pull request by ma4nn**
This PR introduces a new dashboard widget to show a simple descriptive text next to the KPIs that is wrapped correctly and displayed in the regular font style.
By using the `StyledLabel` component the user can also use some simple markup like `<green>`, `<red>`, `<strong>`, `<em>` and `<a>`.

### CODE REVIEW

**Comment by buchen** [comment]
Looks good to me. Thanks for your contribution.

**Comment by buchen** [comment]
Bildschirmfoto 2022-07-17 um 11 28 26

I'll slightly tweak the context menu...

**Comment by buchen** [comment]
I wonder if we should rename it to "Note" (Notiz). After all it is something that the user enters, not an existing description.

**Comment by buchen** [comment]
rebased and merged

**Comment by ma4nn** [comment]
> I wonder if we should rename it to "Note" (Notiz). After all it is something that the user enters, not an existing description.

@buchen yes, good idea 👍 But better leave the widget type now as it is and only change the labels/translations as otherwise the existing widget data will be lost, right? Shall I create a new PR for the renaming?

**Pull request closed without merging**
