### PR TITLE
WIP: French translation

### PR DESCRIPTION
**Pull request by Skymirrh**
Hello, I've started working on the French translation! It also includes some minor modifications to other stuff (e.g. adding missing VES currency), which I have flagged in separate commits for easy spotting, which should help if you want to amend them with additional localizations, or relocate them to another PR.

### CODE REVIEW

**Comment by buchen** [comment]
Hi @Skymirrh,

thanks for starting the translation to French. 😄 🇫🇷 

I have cherry picked the "generic" changes (say to the currencies) and merged them already into master. Additionally, I created a branch [feature_fr](https://github.com/buchen/portfolio/tree/feature_fr) that you can use to push more translations. Or simply push to your existing PR.

Alternatively, you can also use the POEditor to translate the labels. If you register https://poeditor.com/join/project/4lYKLpEWOY then I can approve you to edit the French labels. This might be easier - depending on your workflow. I have uploaded your translations to the POEditor site already.

Andreas.

**Comment by Skymirrh** [comment]
Thanks for the details! I actually don't really care about either:
- Using the `feature_fr` branch or this PR.
- Using POEditor or directly editing the property files (the ResourceBundle Editor plugin works quite well). I can also both maintain POEditor and making sure it's in sync with the code, should that be the easiest solution.

May I suggest you instead tell me what you'd prefer? I intend to continue maintaining the French translation afterwards, so perhaps defining the workflow right now would be best 😃

**Comment by Skymirrh** [comment]
PS: I recently discovered [Weblate](https://weblate.org/en/) and was thinking of playing with it at some point, perhaps if you're also interested we could try to set it up for Portfolio Performance, see how it fares compared to POEditor?

**Comment by buchen** [comment]
> I can also both maintain POEditor and making sure it's in sync with the code, should that be the easiest solution.

I have a couple of scripts that sync between POEditor and the source repository - so maintaining both is not necessary. If you feel comfortable with the ResourceBundleEditor, then maintain it in Git and push against the branch.

Let me know if you want me to build a test version.

> I recently discovered Weblate

Interesting. It looks like it could work directly with the source repository which would make it easier to resolve conflicts (currently, it is manual effort to sync because labels can be changed in the source repository as well as on POEditor).

I do not have the time at the moment to play around with Weblate. The files I am translating are configured here: https://github.com/buchen/portfolio/blob/master/portfolio-app/releng/translation-config.xml From the form to request a new project, it was unclear if I can configure multiple translation files.

**Comment by Skymirrh** [comment]
Hello, made some progress today but I don't have the rights to push to your repository. I'll continue pushing against my fork until I have the rights here :)

**Comment by buchen** [comment]
Hi @Skymirrh,

BTW, in the past I have used Google Translate to get a "baseline" translation. One can copy paste parts of the properties files (roughly 4000 characters) to the translate.google.com UI. It will keep the key = value syntax, but (sometimes) mangle up the placeholders ({0}). Maybe it is easier to correct an existing translations than always translate from scratch?

**Comment by Skymirrh** [comment]
Thanks for the tip! I do use Google Translate to get a baseline when translating sentences, though for single words I find it easier to translate immediately, as single words from the finance vocabulary are a tad too specific for Google Translate to properly translate without context.

I'll continue progressing whenever I have some free time, don't hesitate to let me know re: branches (see previous comment).

**Comment by buchen** [comment]
Hi, I see you are getting along:

Bildschirmfoto 2020-06-27 um 08 34 00

**Comment by Skymirrh** [comment]
I'm actually further than that, only the big `portfolio\ui\messages.properties` remains and I'm halfway through 😄

**Comment by Skymirrh** [comment]
Hello, sorry for the silence I was quite busy the last few weeks!

I have finished translating the whole file. Looks okay-ish!

image

Now that I'm done, I am going to make a consistency pass in order to normalize several terms for which I have used different translations. I have noticed the English version to also be inconsistent, and will try to fix it at the same time.

I have pushed the current state to my fork, and will also open a separate PR with fixes for other languages noticed along the way.

**Comment by buchen** [comment]
Hi @Skymirrh,

I took some time as I was away from my laptop from some weeks. I have now rebased and merged your translation into the master branch. It looks quite nice 😄 I have also updated the translations on poeditor.com in case you prefer to update individual labels there.

I plan to create a release by the end of August.

Andreas.

**Comment by Skymirrh** [comment]
OK, I hope I'll have the time to do the consistency pass by then :)

**Pull request closed without merging**
