### PR TITLE
Translate Portfolio Performance to Spanish

### PR DESCRIPTION
**Pull request by PabloReyes**
Added the Spanish language to Portfolio Performance. Translated all entries in bundle.properties and messages.properties, as well as adding the new language option in LanguagePreferencePage.java.

Tried to keep all the shortcuts in the toolbar with the same characters.

### CODE REVIEW

**Comment by buchen** [comment]
Muchas gracias!

I will have a look at it next weekend - sorry - will not be possibly earlier. I believe we also should add the Spanish language bundles for the Eclipse Plug-ins. And there are a couple other languages files (in the plugin name.abuchen.portfolio and some named "labels.properties")

I have to think how to manage this going forward. I am adding labels as I go. And of course I can do so in German and English, but I cannot do so in Spanish. Maybe I try the default with Google translate, but once in while some native speaker has to look over them.

**Comment by PabloReyes** [comment]
Hi @buchen , 
I'll review the labels.properties file, I totally missed it!

I created a Spreadsheet where I paste the properties file, and a different sheet extracts all the keys and english translations. Then, on a new column, it uses Google Translate to translate to Spanish. Another column is where, if the automatic translation is not 100% correct, I add mine, and in another column I mark it as "OK" if I'm 100% with it:
image

Finally, another sheet gets everything together and recreate a new properties file.  

I've found that I have to do most of the translations by myself, since the google translate version of it is not very good.

I'm more than happy to review all properties files from time to time in search of changes. Also, as soon as I have a bit more time, I'll start taking a look at some of the open bugs and try to help there. 

Thanks for the great work.

**Comment by buchen** [comment]
Hi @PabloReyes,

I have added the Spanish translation to the main branch.

If you want to try:
* [64bit Windows](https://www.dropbox.com/s/qbzlo5j9po4u4yn/PortfolioPerformance-0.29.1-SNAPSHOT-win32.win32.x86_64.zip?dl=0)
* [32bit Windows](https://www.dropbox.com/s/znp3bi3l3c12ev9/PortfolioPerformance-0.29.1-SNAPSHOT-win32.win32.x86.zip?dl=0)
* [macOS](https://www.dropbox.com/s/3tl07mx7oxg9f0d/PortfolioPerformance-0.29.1-SNAPSHOT-macosx.cocoa.x86_64.tar.gz?dl=0)

I went through most of the dialogs and also fixed the alignment. Because some Spanish labels are now longer, they were cut off.

BTW, I am using Eclipse with the [Resource Bundle Editor](https://marketplace.eclipse.org/content/resourcebundle-editor#group-details) installed. It shows me all three translations. And it also adds indicators if at least one translation for that label is missing. It might be helpful when we continue to maintain the translation.

bildschirmfoto 2018-04-02 um 09 04 20

I noticed a couple missing translations (labels.properties), etc.
Also, maybe you can check the "Preferences" - I had to reformat so that the dialog is not too wide.

Andreas.

**Comment by buchen** [comment]
(I am closing this PR because the changes are merged. Let's open a new PR for new fixes).

**Comment by PabloReyes** [comment]
Hi @buchen , I didn't know about the resource bundle editor in Eclipse. I'll check it out for the next time. 

Thanks

**Pull request closed without merging**
