### PR TITLE
Reading Dividends from Dutch DeGiro AccountStatement with FX

### PR DESCRIPTION
**Pull request by ah4c**
Dutch DeGiro.nl Account Statements (rekeningoverzicht) report Dividends in foreign currency with the foreign exchange (FX) rate with Dutch text on previous lines. The FX lines were not parsed by the DegiroPDFExtractor class, which meant that the dividends were ignored.

The Dutch text of the FX lines includes "Valuta Creditering" and "Valuta Debitering".

This commit adds the Dutch text to the existing regex for FX lines. It also includes a new JUnit test method and test input file
AccountStatement_Dividends_FX.txt.

Partial Account Statement where dividend is in USD
```
Datum Tijd Valutadatum Product ISIN Omschrijving FX Mutatie Saldo
27-05-2022 07:34 26-05-2022 Valuta Creditering EUR 0,53 EUR 0,53
27-05-2022 07:34 26-05-2022 Valuta Debitering 1,0758 USD -0,57 USD 0,00
26-05-2022 08:08 25-05-2022 ISHARES INFRA GLO IE00B1FZS467 Dividend USD 0,57 USD 0,57
```

This only fixes reading the FX lines. It does not fix the issue of dividend being paid in a different currency than the security, which I see is being discussed in other threads and pull requests. Now, the difference in currencies is visible in the dialog when importing account statement and transaction.

Partial Transaction PDF for same security in EUR
```
21-04-2022 09:05 ISHARES INFRA GLO IE00B1FZS467 EAM XAMS 1 32,40 EUR -32,40 EUR -32,40 EUR -32,40 EUR
```

See forum post https://forum.portfolio-performance.info/t/pdf-import-from-degiro/12145/73?u=egal

### CODE REVIEW

**Comment by buchen** [comment]
@ah4c  thanks for the contribution - I just created a new release w/o seeing this PR. Next version.

LGTM - @Nirus2000 what do you think?

**Comment by Nirus2000** [comment]
Hello @ah4c 
Please rename the _AccountStatement_Dividends_FX.txt_ to _Rekeningoverzicht03.txt_

Also rename the test case name to _testRekeningoverwaiver03_ and sort the test case in the 
clean order as the other test cases.

As an example, take [testAccountStatement01()](https://github.com/buchen/portfolio/blob/1d315034af0aabcbfa4224f34c9a6153a0d4c848/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/degiro/DegiroPDFExtractorTest.java#L1442) as a template.

There are also several transactions. Please add these. If there are a lot of transactions, I take only a few, but with these three transactions it would be great if all of them appear in the test case.

Good Job 👍🏻

**Comment by buchen** [comment]
I'll do the renaming and merge.

> There are also several transactions. Please add these. If there are a lot of transactions, I take only a few, but with these three transactions it would be great if all of them appear in the test case.

I see only one transaction in the file. The other two lines are the exchange of foreign currency.

**Comment by buchen** [comment]
Thanks @ah4c  for the contribution 😄 👍

**Comment by ah4c** [comment]
Ah, I see that you made similar changes to those that I made at the same time. You were too quick :)

**Pull request closed without merging**
