### PR TITLE
Improve IBFlex-Query-Importer to support new transaction + Fix

### PR DESCRIPTION
**Pull request by Nirus2000**
Improves the processing of the attributes "netCash" and "cost" based on the #3177 [comments from @pfalcon](https://github.com/buchen/portfolio/pull/3177#discussion_r1164700916).

Thanks @pfalcon for the tip and review.

**Summary of changes:**

- [x] Improves the processing of the attributes "netCash" and "cost" 
   - based on the #3177 comments from @pfalcon.
   - based on https://github.com/buchen/portfolio/pull/3280#issuecomment-1508167048 from @pfalcon 
   - Add testfile with testiBFlexStatementFile16() check and set
- [x] Add new assetCategory = fund 
   - https://forum.portfolio-performance.info/t/interactive-brokers-flex-query-importer-not-importing-fund-trades/23714/4
- [x] Remove CFD Trading transaction 
   - Here still unclear how the transaction should be made, as this was not conclusively clarified in PR #1837.
   - testiBFlexStatementFile13() deactivated
- [x] Fix Options and Futures 
   - After implementation by PR e99c44d no tests were inserted to verify the function correctly. Since there were also no tests for older tests because they were simply missing, they were added with PR #3177. Now we fix this testiBFlexStatementFile02() #Trade-3
- [x] Improve trade date and trade time
- [x] Fix testiBFlexStatementFile12.xml and testiBFlexStatementFile12()
   - In PR #3177 the test file was taken from the post https://forum.portfolio-performance.info/t/interactive-brokers/276/122 to check the correct function of the importer. However, this was manipulated in the dates.
The element "dateTime" agrees in the specification to the "tradeDate" and deviates by one year. The original test file, but with too much anonymization of the data, can be found in the article https://forum.portfolio-performance.info/t/interactive-brokers/276/115.

### CODE REVIEW

**Comment by pfalcon** [comment]
@Nirus2000, Thanks for prompt response to my comment and preparing this patch! I tried to look towards your request to provide data which triggered a problem, but that's 3rd-party data which I couldn't share. But I asked for some anonymized extract, and attach it here. It show the nature of the problem - in a sell transaction that we see, "cost" seems to be the original cost basis of the transaction (i.e. buy price times quantity, adjusted for commission). Thus, this patch doesn't really help. If you import it, you get zero balance in Portfolio Performance, while the expected balance is positive 99.37 (bought at 100, sold at 200, minus two commissions).

The problem lies here:
```
                // If the element contains both the "netCash" and "cost"
                // attributes and the values are not equal, set the amount based on
                // the value of the "cost" attribute.
```

Per what I see, it should be the other way around - "netCash" should prevail, while "cost", when it differs from "netCash", means something completely different than the amount which should go into a cash account. Granted, I have very limited experience with these XMLs, perhaps you can point me to a case where "cost" provides the right information, while "netCash" doesn't (I assume such a case would be available among the test XML - thanks for including such, I hope attached XML can serve as a basis for test too).

[TSLA.zip](https://github.com/buchen/portfolio/files/11230239/TSLA.zip)

**Comment by pfalcon** [comment]
> perhaps you can point me to a case where "cost" provides the right information,

Ok, I ran the testsuite with a trivial patch at the end of this comment. The failures with my comments are:

```
Failures: 
  IBFlexStatementExtractorTest.testiBFlexStatementFile02:670 
Expected: is <9>
     but: was <8>
```

The culprit appears to be 

Trade currency="USD" symbol="ORCL  170915P00050000" exchange="--" isin="" cusip="" conid="268828466" description="ORCL 15SEP17 50.0 P" buySell="BUY" tradeDate="20170915" reportDate="20170915" underlyingConid="272800" underlyingSymbol="ORCL" putCall="P" transactionType="BookTrade" quantity="1" tradePrice="0" tradeMoney="0" ibCommission="0" ibCommissionCurrency="USD" **assetCategory="OPT"** accountId="U1234567" acctAlias="" model="" fxRateToBase="0.83701" securityID="" securityIDType="" issuer="" multiplier="100" strike="50" expiry="20170915" principalAdjustFactor="" tradeID="1908991474" tradeTime="162000" settleDateTarget="20170918" proceeds="-0" taxes="0" **netCash="0"** closePrice="1.26" openCloseIndicator="C" notes="A" **cost="49.5"** fifoPnlRealized="0" fxPnl="0" mtmPnl="126" origTradePrice="0" origTradeDate="" origTradeID="" origOrderID="0" clearingFirmID="" orderReference="" volatilityOrderLink="" exchOrderId="N/A" extExecID="N/A" orderTime="" openDateTime="" holdingPeriodDateTime="" whenRealized="" whenReopened="" levelOfDetail="EXECUTION" changeInPrice="0" changeInQuantity="0" orderType="" isAPIOrder="N" /

The first immediate thing we see is that PortforlioPerf doesn't seem to create a transaction with amount of 0 (that's why the test complains that there're 8 xacts instead of expected 9).

Looking at the entry itself, we see that it's assetCategory="OPT". I never looked at options, and making my statement ("netCash should prevail over cost") based only about looking at STK. But let me push forward with that idea (kinda like devil's advocate; it's sad that one needs to make up such theories, but correct me if I'm wrong, there's no official doc about the IB Flex XML). Again, that's first time I look at OPT XML entry, and have a very limited knowledge about options in general. But: that clearly looks like an entry about option *expiration* (see all of symbol, date, and expiry attrs). And yeah, AFAIK, if an option expires "out of money", then yeah, there's no money. So, yeah, it was initially sold for 49.5 (xact in that file before the shown), but then it expired. Yeah, it cost 49.5, but once it expired, no money was credited or debited (netCash="0").

```
  IBFlexStatementExtractorTest.testiBFlexStatementFile11:1710 
Expected: is <EUR 344.57>
     but: was <EUR 344.56>
```

Well, this is a typical rounding issue, we saw that in real life too - a few cents difference with what IB reports show.

```
  IBFlexStatementExtractorTest.testiBFlexStatementFile13:2109 
Expected: is <EUR 1,063.29>
     but: was <EUR 4.24>
```

Trade currency="USD" **assetCategory="CFD"** symbol="QQQXn" description="USD QQQX" isin="" reportDate="20200909" exchange="IBUSCFDMS" quantity="50" tradePrice="25" cost="1255" fifoPnlRealized="0" buySell="BUY" accountId="U123456" acctAlias="" model="" fxRateToBase="0.84724" conid="290662729" securityID="" securityIDType="" cusip="" listingExchange="" underlyingConid="177490870" underlyingSymbol="QQQX" underlyingSecurityID="US6706991071" underlyingListingExchange="NASDAQ" issuer="" multiplier="1" strike="" expiry="" tradeID="" putCall="" principalAdjustFactor="" dateTime="20200909;112233" tradeDate="20200909" settleDateTarget="20200911" transactionType="ExchTrade" tradeMoney="1250" proceeds="-1250" taxes="0" ibCommission="-5" ibCommissionCurrency="USD" netCash="-5" closePrice="25.00" openCloseIndicator="O" notes="" fxPnl="0" mtmPnl="0" origTradePrice="0" origTradeDate="" origTradeID="" origOrderID="0" clearingFirmID="" transactionID="N/A" ibOrderID="N/A" ibExecID="N/A" brokerageOrderID="N/A" orderReference="" volatilityOrderLink="" exchOrderId="" extExecID="" orderTime="--" openDateTime="" holdingPeriodDateTime="" whenRealized="" whenReopened="" levelOfDetail="EXECUTION" changeInPrice="0" changeInQuantity="0" orderType="LMT" traderID="" isAPIOrder="N" accruedInt="0"/

Again, non-STK case, this time assetCategory="CFD". Playing devil's advocate again, as I have no idea how CFD's are treated by IB. But, the whole idea of "Contract For Difference" is that it's leveraged instrument, and you don't pay the whole price of the underlying security. So, what we see above is that a CFD was bought for 50 shares of 25USD each, and there commission was 5USD. Total cost was 1255USD (cost="1255"), but only the commission of 5 was taken from the cash account (netCash="-5"). The rest is went on user's margin account (they'll pay for it with real cash if they get a margin call, and never otherwise; they pay/receive only difference of start/end costs when they close the CFD).


So again, I don't see a contradiction with my claim that: "netCash" should be used for all amounts against a cash account, a "cost" should never be used. (The tests above should be updated. Of course, if it's possible to ask users from which they originated what they actual balance they were seeing after those xacts, it would be nice.)

If you don't want to go that brave, then I at least would suggest to apply "always netCash" rule for assetCategory="STK" (which should cover ETFs too AFAICT).

Thanks!


The test failures were when run with this patch:

```
--- a/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/ibflex/IBFlexStatementExtractor.java
+++ b/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/ibflex/IBFlexStatementExtractor.java
@@ -336,17 +336,17 @@ public class IBFlexStatementExtractor implements Extractor
             String currency = asCurrencyCode(element.getAttribute("currency"));
 
             // Set amount which is "netCash" or "cost"
-            if (element.hasAttribute("cost"))
+            if (element.hasAttribute("netCash"))
             {
                 Money amount = Money.of(asCurrencyCode(element.getAttribute("currency")),
-                                asAmount(element.getAttribute("cost")));
+                                asAmount(element.getAttribute("netCash")));
                 setAmount(element, transaction.getPortfolioTransaction(), amount);
                 setAmount(element, transaction.getAccountTransaction(), amount, false);
             }
             else
             {
                 Money amount = Money.of(asCurrencyCode(element.getAttribute("currency")),
-                                asAmount(element.getAttribute("netCash")));
+                                asAmount(element.getAttribute("cost")));
                 setAmount(element, transaction.getPortfolioTransaction(), amount);
                 setAmount(element, transaction.getAccountTransaction(), amount, false);
             }

```

**Comment by pfalcon** [comment]
@Nirus2000:

> Overall it is the result from years where no tests were added for changes to the importer or the tests are simply incomplete.

Thanks for your work to resolve those issues, much appreciated! Confirming that with this patch as merged, the import with our data works as expected. Thanks again!

**Comment by arnishow** [comment]
Hi,
Any reason why assetCategory="FUT" is missing in that file?
Thanks

**Comment by Nirus2000** [comment]
Hello @arnishow 
create an issue in Github and explain what a "FUT" is, how it should be posted in PP and attach a sample file.

**Pull request merged**
