### PR TITLE
Add new Sedol security idenitification for new AJ Bell Securities Limited PDF-Importer

### PR DESCRIPTION
**Pull request by Nirus2000**
https://forum.portfolio-performance.info/t/pdf-import-from-ajbell-youinvest/21679
https://forum.portfolio-performance.info/t/pdf-import-from-aj-bell-securities-youinvest/21679/3
Add new datetime format in PDFExtractorUtils.java

Add new "_Sedol_" security idenitification for PDF Importer (same like _ISIN_ or _WKN_)
[https://en.wikipedia.org/wiki/SEDOL](https://en.wikipedia.org/wiki/SEDOL)

Hello @buchen 
i for this PDF importer a new security identifier is needed. This I have hopefully been able to implement completely.  I add also some new testCase and improve some source code.
At least I tried :grimacing:

However, I failed with the implementation in the protobuf. I don't understand this one. 
If necessary, something would still have to be triggered via the client factory that updates the existing securities.

Greetings
Alex

### CODE REVIEW

**Comment by buchen** [comment]
(grrr... I just typed up a long response and now the input field is empty again 😬... let me type up the short version)

I never heard about Sedol. I understand it as a country-local security identification number very similar to the WKN (which is the local identification number for Germany).

And reading the Wikipedia, one is also convertible:
> SEDOLs serve as the [National Securities Identifying Number](https://en.wikipedia.org/wiki/NSIN) for all securities issued in the United Kingdom and are therefore part of the security's [ISIN](https://en.wikipedia.org/wiki/International_Securities_Identification_Number) as well.

and
> For British securities, SEDOLs are converted to ISINs by padding the front with two zeros, then adding the country code on the front and the ISIN check digit at the end.

I am hesitant to add new fields. Maybe the mistake was already to add "WKN" (which is the German Wertpapierkennnummer). If we add something for the Britisch/Irish, then what about the French, Spanish, ...?


What can we do?

* We could "rebrand" the WKN as the "country-specific security identifier" (rebrand because we cannot rename it in the XML for compatibility reasons). If the users enters the Sedol in the WKN field, it will just work.
* We could construct the ISIN out of the Sedol and then use the ISIN to identify the security
* We could extend the attribute mechanism to allow for arbitrary local security identifier. The users could configure as many as they want (and even custom ones like the idNotation which is used by popular websites)

**Comment by Nirus2000** [comment]
Hello @buchen

> (grrr... I just typed up a long response and now the input field is empty again 😬... let me type up the short version)

I know, this has also happened to me several times... :disappointed: :disappointed: :disappointed:

---

I understand your point of view.
In principle I know 6 major security identification systems.
- ISIN
- WKN
- CUSIP
- VALOR
- SEDOL
- FIGI

The CUSIP is used e.g. in IBFlexQuery or also in the Score Priority Corp. PDF importer. 
The valor numbers mostly in the Swiss PDF importers.... and so on.

Let's make a separate branch for this again, then I can do some of the work again. 👍🏻 

I like the idea that we convert the WKN into a country specific security identifier. 
I have also already searched the net to see if there is a source on how to convert these. 
([https://www.isindb.com/](https://www.isindb.com/))

What would we need to consider?
- How do we do the recognition of which system it is?

Ah... there I went again with a hit.... well, PP is developing globally and we should set the course for this.
The slovak translation is already finished... #2893 ... unbelievable how fast this is going forward.

Greetings
Alex

**Comment by buchen** [comment]
> In principle I know 6 major security identification systems.

❤️ 

Thanks. That is a nice overview. This is something we can target. (And then we can throw in the notationId for good measure).

Before we implement, let's try to understand some boundary conditions. Can a security have a WKN (german identification) *and* and Sedol (British) at the *same time*? I am asking because the transformation rules to the ISIN would be different (the British would add the GB, pad some 0, and add the verification nu

**Comment by jamescrowley** [comment]
@buchen to answer one of your questions - yes, it's possible for a security to have both a SEDOL and a WKN. I found the following from a random Google:

ISIN: LU0346392219
SEDOL: BNTC223
WKN: A0NGXR
Bloomberg: FFGINCY LX

(https://www.fidelityinternational.com/FILPS/Documents/en/current/ret.en.xx.LU0346392219.pdf)

I'm guessing it's common when listed on multiple exchanges.

**Comment by Nirus2000** [comment]
Hello @buchen
I am absolutely with you on this.

As @jamescrowley mentioned, a security can have any or all of these identification numbers.
Another constraint is that the quotes can also be searched with each of these identification numbers.
I'm also thinking of a simple DropDown field where we set a HashMap and add an "_idNotation_" to it.
A pre-check, could be created by a syntax comparison and then check it. If a unique syntax is found e.g. ISIN.

**ISIN:**
Patter: `^(([A-Z]{2})([A-Z0-9]{9}))(\d{1})$` -> [Mathematical ](http://www.pruefziffernberechnung.de/I/ISIN.shtml)

**WKN:**
Patter: `([ABCDEFGHJKLMNPQRSTUVWZ0-9]{6})` -> [Mathematical ](https://www.isin.net/wkn/)
(Patter; excludes the letters "I" and "O")

**CUSIP:**
Patter: `^([A-Z0-9\*@#]{8})(\d{1})$` -> [Mathematical ](https://www.cusip.com/identifiers.html?section=CUSIP#/CUSIP)

**VALOR:**
Patter: `^([A-Z0-9]{5,9})$` -> [Mathematical ](http://www.pruefziffernberechnung.de/P/Paritaet.shtml)

**SEDOL:**
Patter: `^([A-Z0-9]{6})(\d{1})$` -> [Mathematical ](https://en.wikipedia.org/wiki/SEDOL)

**FIGI:**
Patter: `^([BBG]{3})([A-Z0-9]{7})[\d]{1}$` -> [Mathematical ](https://www.openfigi.com/assets/content/figi-check-digit-2173341b2d.pdf)

**Comment by loucasal** [comment]
@Nirus2000 any reason this was closed? It would be great to have this work brought to fruition eventually.

**Comment by Nirus2000** [comment]
@loucasal it is ready with https://github.com/portfolio-performance/portfolio/pull/3695 and will be released with the next version, as far as everything is ok.

**Pull request closed without merging**
