### PR TITLE
Modify ING PDF-Importer to support account transactions

### PR DESCRIPTION
**Pull request by davidm3i**
This adds support for PDF import of account transactions for the ING bank.

### CODE REVIEW

**Comment by davidm3i** [comment]
I hope I adhered to all guidelines and workflows. Let me know if changes are required.

**Comment by Nirus2000** [comment]
Hello @davidm3i 
I have looked at your pull request. First of all super introduction to start impementation.
Unfortunately there are some critical bugs in the source code.
If you want, we can fix it via TeamViewer on your PC.
Send me to Email at webmaster [at] nirus-online [dot] de

**Comment by davidm3i** [comment]
Thanks for looking through it and pointing out problems. I think all changes were clear to me. I added a few more missed \\ and adapted the test code a bit such that everything should hopefully check out with the new commit.

**Comment by buchen** [comment]
squashed and merged.

**Pull request closed without merging**
