### PR TITLE
Support to open bookmark for multiple securities

### PR DESCRIPTION
**Pull request by OnkelDok**
Sometimes it would be helpful to be able to open bookmarks for several securities at the same time.

I think I have also read a similar request in the forum as sidenote of a post, but I cannot find it.

grafik

### CODE REVIEW

**Comment by chirlu** [comment]
Uh, this seems dangerous to me. You might accidentally get hundreds of browser windows open over each other …

When I first read the title, I actually thought it would open *one* bookmark that accepts a list of parameters, such as the Fondsweb comparison page: https://www.fondsweb.com/de/vergleichen/ansicht/isins/IE00B14X4Q57,IE00B3VTMJ91,LU1650487413

**Comment by buchen** [comment]
> You might accidentally get hundreds of browser windows open over each other …

Shall we limit it to 10 securities max?
If the user accidentally opens the bookmarks, it is okay to close 10 tabs in the browser, but not 100

**Comment by OnkelDok** [comment]
> Uh, this seems dangerous to me. You might accidentally get hundreds of browser windows open over each other …

Good point. We can display a confirmation message when the user has selected more than X (maybe 10 or 15?) securities.

> When I first read the title, I actually thought it would open one bookmark that accepts a list of parameters, such as the Fondsweb comparison page: https://www.fondsweb.com/de/vergleichen/ansicht/isins/IE00B14X4Q57,IE00B3VTMJ91,LU1650487413

Thats an interesting idea. Maybe as additional feature in the future? Do you know other pages that accepts multiple parameters for comparison? For this we would need additional bookmark or bookmark-placeholder with which the user can flag that multiple securities should be joined together into one bookmark with a configurable string as separator.

**Comment by chirlu** [comment]
I don’t think everything that could be implemented should be implemented …

**Comment by buchen** [comment]
> I don’t think everything that could be implemented should be implemented …

Which implementation proposal are you commenting? Opening multiple bookmarks is okay from my side (with a limit). Opening one bookmark with multiple parameters I would not do for now - we would have to have a meaningful example first; and then I am not sure if anybody would understand the pattern logic anymore

I'll add the limiter and merge

**Comment by chirlu** [comment]
Yeah, I meant the one-bookmark-with-list-parameter idea.

**Pull request closed without merging**
