### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by dfdario**
These file are by best effort to the Italian localization. I hope this has been done in the right way because I never been involved in the portfolio project before. Please check the code consistency before compile.

### CODE REVIEW

**Comment by dfdario** [comment]
These file are by best effort to the Italian localization. I hope this has been done in the right way because I never been involved in the portfolio project before. Please check the code consistency before compile.

**Comment by buchen** [comment]
Cool @dfdario - I did not have the time to check it so that I could included it into today's release. I'll check later this week and let you know.

Do you want/need a test build? If so, what OS (Windows, macOS, Linux)?

**Comment by buchen** [comment]
Hi @dfdario,

are you registered with the [PP project on POEditor](https://poeditor.com/join/project?hash=4lYKLpEWOY)?

On POEditor, there is already a partial translation to Italian. I have now merged your changes with the one from POEditor. Then I have updated all changes to POEditor.

If you add yourself there, you can also translate there. Generally, I would like to publish the Italian version only if there is a significant translations. Right now it says roughly 50% of the strings are translated. That creates a "mixed" version out English and Italian and I think that does not look professionally.

Bildschirmfoto 2021-02-07 um 19 58 16

Let me know where you want to continue to translate. I will push the changes also as a branch to github. That should then be in sync with the POEditor translation.

**Comment by buchen** [comment]
This is the branch: https://github.com/buchen/portfolio/tree/feature_italian

**Comment by dfdario** [comment]
I just joined POEditor but no way to translate since.
Do I need to be enabled by someone?

**Comment by dfdario** [comment]
I am engaged also in these projects:
Mythtv (uses QTlanguage)
Bigbag_Android (by mail)
Tasks_Android (uses getlocalization)
Every projects has its own tool ;-)

**Comment by dfdario** [comment]
Great!
Now I am in...

**Comment by buchen** [comment]
> Do I need to be enabled by someone?

I just now did.

Both sources work for me: translate in POEditor or translate the message files in the Github project.

**Comment by dfdario** [comment]
I think we can close this topic because of Italian localization on POEditor has completed.
Looking forward to see the results.
Tschüss

**Comment by buchen** [comment]
> I think we can close this topic because of Italian localization on POEditor has completed.
> Looking forward to see the results.

Cool. I have seen already yesterday that you have been very busy.

I will build a test version tonight. What OS build do you need to test it? Windows, macOS, or Linux?

**Comment by dfdario** [comment]
My favorite OS is Linux Debian 10.

**Comment by dfdario** [comment]
Linux is preferred

**Comment by buchen** [comment]
@dfdario 

I have created test build here: https://www.dropbox.com/s/tr2kr7ylgxv8q5y/PortfolioPerformance-0.50.5-SNAPSHOT-linux.gtk.x86_64.tar.gz?dl=0

It should work to unzip it anywhere. You need Java 11 installed.

**Comment by dfdario** [comment]
OK donwloaded now.
I will check translation consistency and reply you when I am done.

**Comment by dfdario** [comment]
I checked today and I changed a few.
The following are those things I haven't find any reference:
1) In the left menu "Holding" should be translated in "Partecipazioni"
2) In settings "Apply and Close" should be translated to "Applica e chiudi"
3) In the Online menu two voices are not translated:
    - Upload to DivvyDiary.com --> Carica su DivvyDiary.com
    - Sync from etf-data.com --> Sinc. da etf-data.com
 
Might be in the future drilling down the menus I found more misleading translations but for now it seems OK for me.

**Comment by dfdario** [comment]
I don't want to bore you with my questions but a friend of mine since his English is a bit rusty would like to have the Italian version for windows. It would be a further test of my localization. If you have a spare time...

**Comment by dfdario** [comment]
I have updated some strings left in the original language before because I wasn't not sure in how to translate them (eg. {0,choice,0#|1#1 year|1<{0,number} years}). Now I have figured out the way they work.
I know I am asking you a bit more effort, but if it would possible to have last update compiled with both windows && Linux I will appreciate. I tried to compile from source by myself but Eclipse terminate with errors either on Linux or Windows 10 (I am a novice).

**Comment by buchen** [comment]
I have just merged the current set of translations into master.

Here is the build for Linux: https://www.dropbox.com/s/tr2kr7ylgxv8q5y/PortfolioPerformance-0.50.5-SNAPSHOT-linux.gtk.x86_64.tar.gz?dl=0

and the one for Windows: https://www.dropbox.com/s/0ianpjdyfl0xurt/PortfolioPerformance-distro-0.50.5-SNAPSHOT-win32.win32.x86_64.zip?dl=0



> In the left menu "Holding" should be translated in "Partecipazioni"

Quite interesting that it is not translated. It is this label:
https://poeditor.com/projects/po_edit?order=&filter=&per_page=20&id=194291&id_language=75&search=ClientEditorLabelHoldings

> In settings "Apply and Close" should be translated to "Applica e chiudi"

Grrrr. Those are labels where I rely on the translation of Eclipse itself. And this does not seem to be translated.

> In the upper menu "Transaction" should be better translated to "Operazione"

Should be this label:
https://poeditor.com/projects/po_edit?order=&filter=&per_page=20&id=194291&id_language=75&search=menu.transactions.label

> In the Online upper menu two voices are not translated:
Upload to DivvyDiary.com --> Carica su DivvyDiary.com
Sync from etf-data.com --> Sinc. da etf-data.com

I have to work on those. Both labels are currently not translatable. Will change that.

**Comment by buchen** [comment]
I'll close this pull request now. Feel free to post more translations updates here.

**Comment by dfdario** [comment]
Since I am now deeply using this gorgeous program, I continuously fine-tune translations at POEditor as I find a better one for the contest. So you will always find last updates at POEditor's site.

**Pull request closed without merging**
